]7;file://sjdeimac/Users/sj/documents/deng/hongDDD
README.md
alert.sh
g
gameServer.sh
t.txt
test.sh
test_usb.sh
]7;file://sjdeimac/Users/sj/documents/deng/hong[?2004h[?1049h[?1h=[?2004h[1;24r[?12;25h[?12l[?25h[27m[m[H[2J[?25l[24;1H"test.sh" 8L, 100C[1;1H#!bin/bash
if [ -f "DDD" ]; then[3;9Hecho "deng"[4;9Hexec 5>dev-debug.log[5;9HBASH_XTRACEFD="5"[6;9Hset -x
fi

[94m~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [22;1H~                                                                               [23;1H~                                                                               [1;1H[?12l[?25h[?25l[m[24;1H[K[24;1H:[?2004h[?12l[?25hq[?25l[?2004l[24;1H[K[24;1H[?2004l[?1l>[?12l[?25h[?1049l]7;file://sjdeimac/Users/sj/documents/deng/hong[?2004h[?1049h[?1h=[?2004h[1;24r[?12;25h[?12l[?25h[27m[m[H[2J[?25l[24;1H"test.sh" 8L, 100C[1;1H#!bin/bash
if [ -f "DDD" ]; then[3;9Hecho "deng"[4;9Hexec 5>dev-debug.log[5;9HBASH_XTRACEFD="5"[6;9Hset -x
fi

[94m~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [22;1H~                                                                               [23;1H~                                                                               [1;1H[?12l[?25h[?25l[m[24;1H[K[24;1H:[?2004hQ[?12l[?25h[?25l[97m[41mE492: Not an editor command: Q[1;1H[?12l[?25h
[3;9H[4;9H[5;9H[6;9H
[8;8H[?25l[m[24;1H[1mrecording @q[m[24;13H[K[8;8H[?12l[?25h[?25l[24;1H[K[8;8H[?12l[?25h[?25l[24;1H[1mrecording @q[8;8H[?12l[?25h[?25l[m[24;1HType  :qa!  and press <Enter> to abandon all changes and exit Vim[1mrecording @q[m[24;13H[K[8;8H[?12l[?25h[?25l[24;1HType  :qa!  and press <Enter> to abandon all changes and exit Vim[1mrecording @q[m[24;13H[K[8;8H[?12l[?25h[24;1H[?2004l[?2004l[?1l>[?1049lVim: Error reading input, exiting...
Vim: Finished.
[24;1H[J